### ISSUE TITLE
no plus account

### ISSUE THREAD

**Issue by mcantsin** [reduzent/watchteleboy#11]
v1.6 tells me:
"login (as 'foobar')...failed (no Teleboy Plus)
In order to comply with the terms of service of Teleboy this script requires a Teleboy Plus account.
Please visit: http://www.teleboy.ch/shop/list"

whereas v1.5 works fine...

Then I read in your changelog: "Only allow Teleboy Plus users (in compliance with the terms of service by Teleboy AG)".

What does this mean!? - Paying my GEMA and/or Billag Bill, this service has to be delivered _without_ a plus account. How would this violate the Teleboy licence!?

**Comment by mcantsin** [comment]
@reduzent I don't blame you but "service public" is dead in this country! Users are forced to pay taxes and interest on all media, be it buying a flash drive, paying Billag bills or be it the business model by Teleboy to stream media which is produced by tax payers money and top-up advertisment.

Your project might have to be forked into a priated one...

**Comment by reduzent** [comment]
@mcantsin  I whole-heartedly agree with you. 

Maybe you contact me privately (Check mail address in the README)

**Comment by mcantsin** [comment]
Let's see what's next: http://www.heise.de/newsticker/meldung/Schweizer-sollen-ueber-Rundfunkgebuehr-abstimmen-2531490.html

**Comment by stucki** [comment]
@mcantsin This has nothing to do with Teleboys advertising. They have costs to run their infrastructure, etc. It's fair to say that only plus users can circumvent that.

The link you mention is about a tax which is not charged by Teleboy. (In fact, it must be paid on top of the Teleboy plus membership.)
