### ISSUE TITLE
Broken grep

### ISSUE THREAD

**Issue by Marius2805** [reduzent/watchteleboy#20]
The newest version of grep brakes the script.
Grep expects an binary format instead of text.

This can be easily fixed by adding -a option to every use of grep.

**Comment by reduzent** [comment]
Thanks for the info. I try not to parse html or json anymore with grep and co. My plan is to only talk to the teleboy API and do proper json parsing with [jq](https://stedolan.github.io/jq/)

**Comment by reduzent** [comment]
Closed
