### ISSUE TITLE
Teleboy html structure changed

### ISSUE THREAD

**Issue by Marius2805** [reduzent/watchteleboy#21]
The script is fetching the following URL:
`http://www.teleboy.ch/programm/?program_date=live`
for an element similar to:
`<tr class="playable">`

This element is not existing anymore. Maybe the structure changed only a bit and a minor change of the grep pattern could fix this.
But unfortunately I don´t know, how the HTML structure looked before.
Does anybody have an idea?

**Comment by reduzent** [comment]
Current version doesn't use that URL anymore. It uses the teleboy API (http://tv.api.teleboy.ch) and parses the JSON with jq. 

NOTE: jq is a new dependency of watchteleboy. It'll automatically gets installed, if you install watchteleboy as .deb package from [launchpad](https://launchpad.net/~reduzierer/+archive/ubuntu/reduzent)
