### ISSUE TITLE
Just print URL

### ISSUE THREAD

**Issue by flowlee** [reduzent/watchteleboy#27]
Would it be possible to add an option to just print the contents of $HLS_VARIANT_URL for the specified channel without starting playback?

This output could then be used in external players or in a cron job for creating playlists.

**Comment by reduzent** [comment]
I see how this could be useful. I'll look into it when I find time. 

Your cronjob example isn't actually good example for this, because the final URL is only valid for a certain period and watchteleboy already has an interface for creating cronjobs.

**Comment by NeySlim** [comment]
The url is valid for a very long period of time. I have streams using the same url from last november.
I modifed watchteleboy to print the index.m3u8 URL for an asked channel, the only problem is for each channel it generates a new session.

Maybe could be a good thing to print the url for all channels.

**Comment by reduzent** [comment]
I have rewritten the script in Python, since Teleboy switched from Apple HLS to MPEG-DASH. The new Python version has an option `--print-url` that only prints the URL of the manifest (mpd file).

**Comment by reduzent** [comment]
BTW: I wonder how long those URLs are valid. If they are permantenly, the whole thing of dealing with logins and sessions and teleboy API would be obsolete. I also wonder if the URL is associated with the login session in any way.

**Comment by NeySlim** [comment]
> BTW: I wonder how long those URLs are valid. If they are permantenly, the whole thing of dealing with logins and sessions and teleboy API would be obsolete. I also wonder if the URL is associated with the login session in any way.
At least 6 month. I think it's a year.
Thanks for the new print url method, I can use it with vlc since ffmpeg doesnt like teleboy mpd.

**Comment by reduzent** [comment]
They are valid not longer than a few days. And it seems there is no association with the Teleboy-Login.
