### ISSUE TITLE
No more login allowed. Cloudflare blocks the curl post data

### ISSUE THREAD

**Issue by shorewall** [reduzent/watchteleboy#28]
Hi,
I've always logged in fine using the script but starting from a few says ago the login fails.
A quick debug show that the login request (made by a curl post) receives back a cloudflare challenge page.
No problem using a  browser and the same credentials.

curl --user-agent 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:12.0) Gecko/20100101 Firefox/12.0'  --cookie-jar /tmp/watchteleboy/xxxxxxxxxx/cookie0  https://www.teleboy.ch/en/login
Response: Cf challenge page

**Comment by shorewall** [comment]
Solved. I just login once to Teleboy using my browser. Then on the fly the script will'extract the cinergy_s cookie by a simple query from the Firefox cookies db. 
No more login needed. :-)

**Comment by reduzent** [comment]
Glad to hear. I wasn't able to reproduce this. But it's good to know about how you solved it, just in case someone experiences something similar.
