### ISSUE TITLE
DDOS prevention breaks watchteleboy

### ISSUE THREAD

**Issue by reduzent** [reduzent/watchteleboy#33]
The script has stopped working for a few weeks now. When running it, it quits with the error:

```console
$ watchteleboy
failed to retrieve channel ids
Traceback (most recent call last):
  File "/usr/bin/watchteleboy", line 102, in <module>
    main()
  File "/usr/bin/watchteleboy", line 59, in main
    wtgui = wt.WatchTeleboyGUI(wts, player)
  File "/usr/lib/python3/dist-packages/wt/gui.py", line 48, in __init__
    self.channels = self.wt_session.get_channels()
  File "/usr/lib/python3/dist-packages/wt/classes.py", line 89, in get_channels
    chanlist = list(self.channel_ids.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

After finding POST requests in the Firefox console containing `jschl_vc` and `jschl_answer`, i believe the reason is cloudflare's DDOS protection. Check here:

https://khromov.wordpress.com/2013/02/05/cloudflare-client-side-ddos-detection-how-does-it-work/

**Comment by useretail** [comment]
Any solutions?

**Comment by reduzent** [comment]
Yeah, version 2.2 uses the new teleboy API key. It works again with this version. 

See: https://github.com/reduzent/watchteleboy/releases/tag/v2.2

The bug report is bogus as the problem is _not_ DDOS protection. (Although in the browser, I get the javascript challenge)

**Comment by reduzent** [comment]
I close this issue as it seems resolved
