### ISSUE TITLE
RTL Gruppe

### ISSUE THREAD

**Issue by apprenticius** [reduzent/watchteleboy#34]
Die Streamer der Sender Gruppe von RTL (RTL, RTL2, SUPER RTL, VOX) kann nicht abgespielt werden. Gibt es einen Grund?

Vielen Dank für die tolle Arbeit,
Apprenticius.

**Comment by reduzent** [comment]
Danke für den Report. Ich hab es auch schon festgestellt. Ich werde dem Grund bei Gelegenheit nachgehen.

**Comment by reduzent** [comment]
Interesting, I can actually still access fragments of the RTLch stream by replacing elements in the URL of the manifest file:
```
zh2-17-dashenc-live.zahs.tv -> zh2-3-dash-live.zahs.tv
m_drm_widevine.mpd -> m.mpd
```

```
$ mpv "http://zh2-17-dashenc-live.zahs.tv/HD_rtl_schweiz/m_drm_widevine.mpd?z32=MF2WI2LPL5RW6ZDFMNZT2YLBMMTGG43JMQ6TCNZSHBATIMZUGJDEGOBWIZCEGLJSHBBDONKCG42TIQRQG5DECOJZEZWWC6DSMF2GKPJVGAYDAJTNNFXHEYLUMU6TEMJQEZYHEZLGMVZHEZLEL5WGC3THOVQWOZJ5MRSSM43JM46TCNS7HEYDSMZSGM4TQNRYGVRGENRSMMYTANZYGNSTAZTGGBRTGYJSGRQSM5LTMVZF62LEHV2GK3DFMJXXSOR2G44TEMZYHATHMPJQ"
[ytdl_hook] ERROR: [generic] m_drm_widevine: This video is DRM protected 
[ytdl_hook] youtube-dl failed: unexpected error occurred 
Failed to recognize file format.

Exiting... (Errors when loading file)
```
Now, with replacements applied:

```
mpv "http://zh2-3-dash-live.zahs.tv/HD_rtl_schweiz/m.mpd?z32=MF2WI2LPL5RW6ZDFMNZT2YLBMMTGG43JMQ6TCNZSHBATIMZUGJDEGOBWIZCEGLJSHBBDONKCG42TIQRQG5DECOJZEZWWC6DSMF2GKPJVGAYDAJTNNFXHEYLUMU6TEMJQEZYHEZLGMVZHEZLEL5WGC3THOVQWOZJ5MRSSM43JM46TCNS7HEYDSMZSGM4TQNRYGVRGENRSMMYTANZYGNSTAZTGGBRTGYJSGRQSM5LTMVZF62LEHV2GK3DFMJXXSOR2G44TEMZYHATHMPJQ"
Resuming playback. This behavior can be disabled with --no-resume-playback.
 (+) Video --vid=1 (*) (h264 1280x720)
 (+) Audio --aid=1 --alang=eng (*) (aac 2ch 48000Hz)
Using hardware decoding (vaapi).
AO: [jack] 44100Hz stereo 2ch floatp
VO: [gpu] 1280x720 vaapi[nv12]
AV: 463545:43:40 / 463545:43:40 (100%) A-V:  0.000 Cache: 0.0s
```

Seems like some servers support only DRM streams while others non-DRM streams

**Comment by apprenticius** [comment]
Ich habe den Grund gefunden und für meine Zwecke behoben. Ich habe gerade keine Zeit, aber kann es dir später mitteilen.

Beste Grüsse,
Elmar.

18.11.2022 09:50:39 Roman Haefeli ***@***.***>:

**Comment by apprenticius** [comment]
du musst die Funktion get_stream_url der Klasse "classes.py" im Ordner "wt" ändern. Sie sollte zusätzlich bei DRM die "license_url" zurückgeben. Betroffen sind somit die letzten 4 Zeilen der Funktion. Der Punkt ist, dass diese Sender DRM verschlüsselt sind und dem Player die "license_url" und das DRM-Schema WIDEVINE mitgegeben werden muss. Da ich nicht den Player verwende in deinem Projekt, kann ich dir nicht genau sagen, wie du diese "license_url" deinem Player übergeben musst.

    def get_stream_url(self, channel=None, station_id=None):
        """
        get MPEG-DASH manifest URL for given channel or station id
        """
        if not self.channel_ids:
            self.__retrieve_channel_ids()
        if station_id is None:
            for chan_name in self.channel_ids.keys():
                if chan_name.lower() == channel.lower():
                    channel = chan_name
                    break
            else:
                print(f'No such channel: {channel}')
                return None
            station_id = self.channel_ids[channel]
        api_url = f'https://tv.api.teleboy.ch/users/{self.user_id}/stream/live/{station_id}'
        r_api = self.api.get(api_url)
        try:
            assert r_api.status_code == 200
        except AssertionError:
            print('failed to retrieve channel data')
            raise WatchTeleboyError
        channel_data = json.loads(r_api.content.decode())
        **if 'drm' in channel_data['data']['stream']:
            return (channel, channel_data['data']['stream']['url'], channel_data['data']['stream']['drm'])
        else:
            return (channel, channel_data['data']['stream']['url'], None)**

Beste Grüsse,
Apprenticius.

**Comment by reduzent** [comment]
Vielen herzlichen Dank für den Hinweis. Ich schau mir an, ob ich das so hinkriege. Um bis zu drei Stunden zeitversetzt schauen zu können, habe ich einen relativen kruden Stream-Handler selber gebaut, der die einzelnen Video- und Audio-Segmente runterlädt. Mal schauen, ob ich das damit und der DRM-Lizenz  hinkriege.  

Als sehr krude, aber offenbar funktionierende Variante, detektiert das Skript jetzt, ob es sich um eine DRM-geschütze Manifest-URL handelt und schreibt dann einfach die URL um. Offenbar sind alle Streams (habe nicht alle getestet) immer noch ohne DRM verfügbar. 

Siehe 31c5ce4e70ab2082819feb56db8f24884e885d94

**Comment by reduzent** [comment]
This is not really fixed, but worked-around in  [v.2.3](https://github.com/reduzent/watchteleboy/releases/tag/v2.3).

**Comment by apprenticius** [comment]
Hallo Roman
Ich habe dein Python Projekt etwas angepasst, so dass ich über die Fernbedienung des Fernsehers via CEC den Sender wechseln kann. Unschön dabei ist, dass der MPV Player jedes mal schliesst und eine neue Instanz öffnet. Dabei erscheint somit jedesmal das OS des Raspberry Pi. Ansonstenist es die perfekte TV-Box. Ist es irgendwie möglich die Pipe (fifo) zu aktualisieren, ohne MPV zu schliessen?

Besten Dank für deine Antwort,
Elmar.

20.11.2022 22:02:37 Roman Haefeli ***@***.***>:
