### ISSUE TITLE
Cronjob command without absolute path

### ISSUE THREAD

**Issue by thonixx** [reduzent/watchteleboy#7]
If I want to record a program and I let the script create the cronjob, then I have this as a result:

```
55 13 19 02 * watchteleboy --record --quiet --channel SRF1 --duration 180 --deleteme 44436002 --showname "SRF1" --path /home/user/watchteleboy
```

Problem: Having watchteleboy not symlinked in one of the systems standard executable paths the cronjob fails to start.
I recommend to set an absolute path to the watchteleboy executable.

**Comment by reduzent** [comment]
Fixed in commit 4a31c4b4
